version: '3'
services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdb:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
    volumes:
      - redis_data:/data
  
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:8.12.2
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

  health_check:
    build:
      dockerfile: ./cmd/health_check/Dockerfile
    container_name: health_check
    depends_on:
      - postgresql
      - elasticsearch
      - kafka
    volumes:
      - ./cmd/health_check/.env:/go/app/cmd/health_check/.env
  
  report:
    build:
      dockerfile: ./cmd/report/Dockerfile
    container_name: report
    depends_on:
      - postgresql
      - elasticsearch
      - kafka
    ports:
      - 50052:50052
    volumes:
      - ./cmd/report/.env:/go/app/cmd/report/.env

  api:
    build:
      dockerfile: ./cmd/api/Dockerfile
    container_name: api
    ports:
      - 8090:8090
    depends_on:
      - postgresql
      - elasticsearch
      - kafka
    volumes:
      - ./cmd/api/.env:/go/app/cmd/api/.env

volumes:
  pgdb:
  redis_data:
  esdata:

networks:
  grpc-net:
    driver: bridge
